language: node_js
node_js:
  - "8"
before_script:
  - npm install -g sfdx-cli
  - echo "$SFDX_AUTH_URL" > /tmp/sfdxurl
  - sfdx force:auth:sfdxurl:store -f /tmp/sfdxurl -a ci-devhub -d
script:
  - sfdx force:org:create -f config/project-scratch-def.json -s
  - sfdx force:source:push
  - sfdx force:apex:test:run -l RunLocalTests -r human --wait 60
